#!/usr/bin/python3

from textwrap import dedent

syscalls = """\
add_thread
get_thread_property
set_thread_property
get_kernel_config
set_kernel_config
yield
get_msg
send_msg
thread_wait
thread_wake
thread_cancel
mutex
condition_variable
open
read
write
lseek
remove
close
exit
malloc
realloc
free
list_dir""".split()

print(dedent("""\
/* Generated by scripts/gen_syscalls.py */
// clang-format off
#ifndef COMMON_SYSCALL_H
#define COMMON_SYSCALL_H
"""))

print(dedent("""\
#include <stddef.h>

typedef enum {"""))
for n, call in enumerate(syscalls):
    print("  syscall_{} = {},".format(call, n))

print(dedent("""\
  syscall_eol,
} Syscall;"""))
print()

print(dedent("""#endif /* ifdef COMMON_SYSCALL_H */"""))
