#! /bin/bash
set -e

# Auto generated script to test the ${NAME} demo.
# Generated by cmake.

cd "${CMAKE_BINARY_DIR}"/demos/"${NAME}"

# Run qemu with serial output into a log file.
# If it exited unexpectedly print the log and fail the test.
# Most often happens on a UBSAN failure.
# QEMU is a command so I can't quote it.
# shellcheck disable=SC2086
${QEMU}${NAME}_kernel -serial file:"${NAME}"_got.log \
  > /dev/null 2>&1 || (cat "${NAME}"_got.log && exit 1)

if [[ "${TEST_TYPE}" == "log" ]]; then
  diff "${CMAKE_SOURCE_DIR}"/demos/"${NAME}"/expected.log "${NAME}"_got.log
elif [[ "${TEST_TYPE}" == "expect" ]]; then
  "${CMAKE_SOURCE_DIR}"/demos/"${NAME}"/expected.exp
else
  echo "Unknown test type ${TEST_TYPE}!"
  exit 1
fi
